import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:url_launcher/url_launcher.dart';

import 'package:news_application_maker/features/ai/providers/ai_provider.dart';
import 'package:news_application_maker/features/ai/services/ai_service.dart';
import 'package:news_application_maker/features/bookmarks/providers/bookmark_provider.dart';
import 'package:news_application_maker/features/news_feed/models/news_article.dart';
import 'package:news_application_maker/features/news_feed/providers/news_feed_provider.dart';
import 'package:news_application_maker/features/preferences/providers/recommendation_provider.dart';
import 'package:news_application_maker/features/preferences/services/event_service.dart';

class ArticleDetailScreen extends ConsumerWidget {
  const ArticleDetailScreen({required this.article, super.key});

  final NewsArticle article;

  Future<void> _openOriginal() async {
    final uri = Uri.parse(article.url);
    if (await canLaunchUrl(uri)) {
      await launchUrl(uri, mode: LaunchMode.externalApplication);
    }
  }

  void _toggleBookmark(WidgetRef ref) {
    final wasBookmarked = ref.read(isBookmarkedProvider(article.url));
    ref.read(bookmarksProvider.notifier).toggle(article);
    if (!wasBookmarked) {
      // Bookmarking is a strong positive preference signal.
      ref.read(recommendationProvider.notifier).record(EventType.bookmark, article);
    }
  }

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final theme = Theme.of(context);
    final bookmarked = ref.watch(isBookmarkedProvider(article.url));
    final fullArticle = ref.watch(articleContentProvider(article));

    return Scaffold(
      appBar: AppBar(
        actions: [
          IconButton(
            tooltip: bookmarked ? 'Remove bookmark' : 'Bookmark',
            icon: Icon(bookmarked ? Icons.bookmark : Icons.bookmark_outline),
            onPressed: () => _toggleBookmark(ref),
          ),
          IconButton(
            tooltip: 'Open original',
            icon: const Icon(Icons.open_in_new),
            onPressed: _openOriginal,
          ),
        ],
      ),
      body: ListView(
        padding: const EdgeInsets.all(16),
        children: [
          Text(article.title, style: theme.textTheme.headlineSmall),
          const SizedBox(height: 8),
          if (article.sourceName.isNotEmpty)
            Text(
              article.sourceName,
              style: theme.textTheme.labelLarge
                  ?.copyWith(color: theme.colorScheme.primary),
            ),
          const SizedBox(height: 16),
          if (article.imageUrl != null)
            ClipRRect(
              borderRadius: BorderRadius.circular(12),
              child: CachedNetworkImage(imageUrl: article.imageUrl!),
            ),
          const SizedBox(height: 16),

          _AiSummaryCard(article: article),
          const SizedBox(height: 16),

          fullArticle.when(
            loading: () => const Padding(
              padding: EdgeInsets.symmetric(vertical: 32),
              child: Center(child: CircularProgressIndicator()),
            ),
            error: (_, __) => Text(
              article.summary.isNotEmpty
                  ? article.summary
                  : 'Could not load the full article. Tap the link icon to open '
                      'the original.',
              style: theme.textTheme.bodyLarge,
            ),
            data: (loaded) => Text(
              (loaded.content?.isNotEmpty ?? false)
                  ? loaded.content!
                  : loaded.summary,
              style: theme.textTheme.bodyLarge?.copyWith(height: 1.5),
            ),
          ),
          const SizedBox(height: 24),
          Center(
            child: FilledButton.tonalIcon(
              onPressed: _openOriginal,
              icon: const Icon(Icons.open_in_new),
              label: const Text('원문 보기'),
            ),
          ),
        ],
      ),
    );
  }
}

/// On-demand AI summary. Generated by the ai-summarize Edge Function (Claude)
/// and cached server-side.
class _AiSummaryCard extends ConsumerStatefulWidget {
  const _AiSummaryCard({required this.article});
  final NewsArticle article;

  @override
  ConsumerState<_AiSummaryCard> createState() => _AiSummaryCardState();
}

class _AiSummaryCardState extends ConsumerState<_AiSummaryCard> {
  bool _requested = false;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final available = ref.read(aiServiceProvider).isAvailable;

    return Card(
      color: theme.colorScheme.surfaceContainerHighest,
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Icon(Icons.auto_awesome,
                    size: 18, color: theme.colorScheme.primary),
                const SizedBox(width: 8),
                Text('AI 요약', style: theme.textTheme.titleSmall),
              ],
            ),
            const SizedBox(height: 8),
            if (!available)
              const Text('AI 요약을 사용하려면 백엔드 설정이 필요합니다.')
            else if (!_requested)
              Align(
                alignment: Alignment.centerLeft,
                child: FilledButton.tonal(
                  onPressed: () => setState(() => _requested = true),
                  child: const Text('3줄 요약 생성'),
                ),
              )
            else
              _summaryBody(),
          ],
        ),
      ),
    );
  }

  Widget _summaryBody() {
    final summary = ref.watch(articleSummaryProvider(widget.article));
    return summary.when(
      loading: () => const Padding(
        padding: EdgeInsets.symmetric(vertical: 8),
        child: Row(children: [
          SizedBox(
              width: 16, height: 16,
              child: CircularProgressIndicator(strokeWidth: 2)),
          SizedBox(width: 12),
          Text('요약하는 중…'),
        ]),
      ),
      error: (e, _) => Text(e is AiException ? e.message : e.toString()),
      data: (text) => Text(text, style: Theme.of(context).textTheme.bodyMedium),
    );
  }
}
